### ISSUE TITLE
Decide on Application Structure

### ISSUE THREAD

**Issue by shiratap** [migrate-life/MigrateLife2#7]
Currently we have a Javascript back end run with a Node/Express server. This can obviously change to fit a C# Server

### Back End
- [ ] Javascript
- [x] C#/.NET

### Front end side, we have a list of libraries/technologies/structures that can work. 
- [x] Server Side Rendering
  - [x] React
  - [ ] Vue
  - [ ] Ember
- [ ] Vanilla JS and HTML
  - [x] Bootstrap
  - [ ] Materialize
  - [ ] Some other styling library

**Comment by Tanner253** [comment]
C# .NET backend forusre,
IDC about rendering or front end technologies

**Comment by jong9000** [comment]
I am pretty agnostic to whatever but the biggest questions for me right now are...

1. What type of database do we need/want?
2.  What are we going to store in the database?

**Comment by Tanner253** [comment]
SQL database - same sort of data, information on a given area - but we need to rework how we find a given area. i take back the .net backend we can redo it all in javascript i need to relearn it anyhow. collab day at codefellows?

**Comment by shiratap** [comment]
> I am pretty agnostic to whatever but the biggest questions for me right now are...
> 
> 1. What type of database do we need/want?
> 2. What are we going to store in the database?

If we're storing user authentication data, probably SQL. I've been using mysql recently, so I might stick to that technology

> SQL database - same sort of data, information on a given area - but we need to rework how we find a given area. i take back the .net backend we can redo it all in javascript i need to relearn it anyhow. collab day at codefellows?

My only available collab day would be Sunday 😅and honestly, you're probably good doing the backend with c#/.net if Ian wants to hop on that train
